package org.github.srtobi.tradewar3

object GameConfig:
  // Stock Market
  val STOCK_MIN_PRICE = 100
  val STOCK_MAX_PRICE = 4000
  val STOCK_MIN_UPDATE_INTERVAL = 0.5f
  val STOCK_MAX_UPDATE_INTERVAL = 2.5f
  val STOCK_PRICE_SIGMA = 600.0
  val STOCK_MEAN_REVERSION_TARGET = 2000.0
  val STOCK_MEAN_REVERSION_FACTOR = 0.05
  val STOCK_BULK_UPGRADE_BASE_COST = 5000L
  val INITIAL_MONEY = 10000L
  val INITIAL_BULK_AMOUNT = 1
  val STOCK_COMPANY_COUNT = 5

  // War Map / Battle
  val UNIT_COST = 1000
  val UNIT_COST_INCREASE = 20
  val BATTLE_INTERVAL_MIN = 1.0f
  val BATTLE_INTERVAL_MAX = 7.0f
  val BATTLE_RANDOMNESS_MIN = 0.2f
  val BATTLE_RANDOMNESS_MAX = 0.35f
  val TERRITORIAL_ADVANTAGE_PER_NEIGHBOR = 0.02f  // 2% less losses per controlled neighbor
  val INITIAL_UNITS = 10
  val NEUTRAL_UNITS_MIN = 5
  val NEUTRAL_UNITS_MAX = 20
  val MAP_RADIUS = 3
  val WAR_EXPANSION_THRESHOLD = 2

  // UI
  val UI_STOCK_PANEL_WIDTH_PERCENT = 0.33f
  val UI_HEX_SIZE = 80f
  
  // Networking
  val DEFAULT_PORT = 12345
